# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  entity-linking:
    volumes:
      - "./annotators/entity_linking:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8075:8075
  wiki-parser:
    volumes:
      - "./annotators/wiki_parser:/src"
      - "./common:/src/common"
    ports:
      - 8077:8077
  knowledge-grounding:
    volumes:
      - "./services/knowledge_grounding:/src"
    ports:
      - 8083:8083
  knowledge-grounding-skill:
    volumes:
      - "./common:/src/common"
      - "./skills/knowledge_grounding_skill:/src"
    ports:
      - 8085:8085
  entity-storer:
    volumes:
      - "./common:/src/common"
      - "./annotators/entity_storer:/src"
    ports:
      - 8089:8089
  dff-bot-persona-skill:
    volumes:
      - "./skills/dff_bot_persona_skill:/src"
      - "./common:/src/common"
    ports:
      - 8105:8105
  dff-wiki-skill:
    volumes:
      - "./skills/dff_wiki_skill:/src"
      - "./common:/src/common"
    ports:
      - 8111:8111
  user-persona-extractor:
    volumes:
      - "./annotators/user_persona_extractor:/src"
      - "./common:/src/common"
    ports:
      - 8114:8114
  entity-detection:
    volumes:
      - "./annotators/entity_detection:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8103:8103
  dialogpt-persona-based:
    volumes:
      - "./services/dialogpt_persona_based:/src"
      - "./common:/src/common"
    ports:
      - 8131:8131
  terminusdb:
    ports:
      - 27017:27017
  entity-extraction-kg:
    volumes:
      - "./annotators/entity_extraction_kg:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 9103:9103
  wiki-parser-kg:
    ports:
      - 9077:9077
  dff-kg-personality-skill:
    volumes:
      - "./skills/dff_kg_personality_skill:/src"
      - "./common:/src/common"
      - "./bin:/src/bin"
    ports:
      - 8058:8058
  property-extraction:
    volumes:
      - "./annotators/property_extraction:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8126:8126
  user-knowledge-graph:
    volumes:
      - "./annotators/user_knowledge_graph:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8127:8127
version: "3.7"
