services:

  personality-catcher:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8010
      - PORT=8010

  dff-intent-responder-skill:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8012
      - PORT=8012

  intent-catcher:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8014
      - PORT=8014

  dff-movie-skill:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8023
      - PORT=8023

  emotion-skill:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8049
      - PORT=8049

  entity-linking:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8075
      - PORT=8075

  wiki-parser:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8077
      - PORT=8077


  knowledge-grounding:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8083
      - PORT=8083

  entity-storer:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8089
      - PORT=8089

  knowledge-grounding-skill:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8085
      - PORT=8085

  dff-animals-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8094
      - PORT=8094

  dff-travel-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8096
      - PORT=8096

  dff-sport-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8098
      - PORT=8098

  dff-food-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8097
      - PORT=8097

  dff-science-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8101
      - PORT=8101

  dff-music-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8099
      - PORT=8099

  dff-bot-persona-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8105
      - PORT=8105

  dff-gaming-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8115
      - PORT=8115

  dff-gossip-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8109
      - PORT=8109

  dff-wiki-skill:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8111
      - PORT=8111

  user-persona-extractor:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8114
      - PORT=8114

  wiki-facts:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8116
      - PORT=8116

  entity-detection:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8103
      - PORT=8103

  dialogpt-persona-based:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8131
      - PORT=8125

  relative-persona-extractor:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8133
      - PORT=8133
version: '3.7'
